### ISSUE TITLE
render is undefined

### ISSUE THREAD

**Issue by panosru** [coolony/kiwi#1]
Hi, I tried this:

``` js
var kiwi = require('kiwi');

kiwi.Template('Hello ${name}', { cache : false }).render({ name : 'panosru'}, function (err, output) {
  console.log(output);
});
```

and I got this:

```
/home/admin/domains/med-app.av/public_html/kiwi/kiwi.js:3
kiwi.Template('Hello ${name}', { cache : false }).render({ name : 'panosru'}, 
                                                  ^
TypeError: Cannot call method 'render' of undefined
    at Object.<anonymous> (/home/admin/domains/med-app.av/public_html/kiwi/kiwi.js:3:51)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)
```

if I remove the `{ cache : false }` I also get this:

```
/home/admin/domains/med-app.av/public_html/kiwi/node_modules/kiwi/lib/template.js:95
  if(options.cache && !(this._getCache() instanceof options.cacheHandler)) {
                             ^
TypeError: Object #<Object> has no method '_getCache'
    at Object.Template (/home/admin/domains/med-app.av/public_html/kiwi/node_modules/kiwi/lib/template.js:95:30)
    at Object.<anonymous> (/home/admin/domains/med-app.av/public_html/kiwi/kiwi.js:3:6)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Array.0 (module.js:484:10)
    at EventEmitter._tickCallback (node.js:190:38)
```

**Comment by panosru** [comment]
Ah... damn I don't instantiate kiwi template... `new kiwi.Template` fixed :)
